spring.application.name=soap_veterinaria_rates
server.port=8098

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:29888/railway?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${BD_MYSQL_CLOUD_PASSWORD}
