app:
  jwt:
    secret: emrYvkqZeg78wQ4cTzPUrP4VmzX13AF8bxc9lqdeFs2

server:
  port: 8092

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: clinsantar@gmail.com
    password: ihfbciddbduvltve
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vitalvet_usuarios?useSSL=false&serverTimezone=UTC
    username: root
    password:
  messages:
    basename: messages
  application:
    name: MICRO-USUARIO
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/