app:
  jwt:
    secret: emrYvkqZeg78wQ4cTzPUrP4VmzX13AF8bxc9lqdeFs2
server:
  port: 8093
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vitalvet_pacientes?currentSchema=pacientes
    username: postgres
    password: sql
  messages:
    basename: messages
  application:
    name: MICRO-PACIENTE
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/